### ISSUE TITLE
Page 114 "and that that field" should read "and that field"

### ISSUE THREAD

**Issue by amaurycrickx** [xuorig/prg-feedback#10]
> and that that field is well protected by our field authorization.

Remove extra "that"

**Comment by amaurycrickx** [comment]
Consider rephrasing "no one without the scope" to "only clients with the scope" to avoid double negation

**Comment by amaurycrickx** [comment]
> Now, imagine as the schema gets more complex, and as different teams start adding their part of the schema:

I'm not sure commas are at the right place... maybe:
Now, as the schema gets more complex and as different teams start adding their part of the schema, here's what could happen:

**Comment by xuorig** [comment]
👍
