### ISSUE TITLE
Page 165 "there are not really any “out of the box” mature GraphQL gateways" -> is plural adequate?

### ISSUE THREAD

**Issue by amaurycrickx** [xuorig/prg-feedback#13]
> there are not really any “out of the box” mature GraphQL gateways

I'd think it should read 
there aren't really any “out of the box” mature GraphQL gateways

or maybe 
there isn't really any off-the-shelve mature GraphQL gateway implementation

Plural vs singular in this case would be all about emphasis so I believe it can go both ways?

**Comment by xuorig** [comment]
good suggestion, implemented in v1.2
