### ISSUE TITLE
Page 171 Broken links

### ISSUE THREAD

**Issue by amaurycrickx** [xuorig/prg-feedback#14]
1. Link includes canadian locale
> A great example of this is Stripe’s approach to versioning.
https://stripe.com/en-ca/blog/api-versioning
-> link is not broken but locale should be removed as the server issues a redirect to the rewritten url: 
In my case, I got a dialog at the bottom of the page asking me if I wanted to switch country

2. Broken link
> For example, the GitHub API allows clients to specify a custom media type that includes a version number.
https://developer.github.com/v3/media/%23request-specific-version

3. Broken link
> In fact, Shopify adopted a URL versioning approach to evolve their GraphQL API.
https://help.shopify.com/en/api/versioning%23the-api-version-release-schedule

**Comment by xuorig** [comment]
Good catches, fixed in v1.2
