### ISSUE TITLE
Page 173 Consider rephrasing 'the same amount of work (possibly more, the amount of versions)"

### ISSUE THREAD

**Issue by amaurycrickx** [xuorig/prg-feedback#15]
> Versioning requires the same amount of work (possibly more, the amount of versions) than if we had a single continuously evolving version.

Had to think twice what was meant with "possibly more, the amount of versions" 

Maybe consider rephrasing to: 
(possibly more, depending on the number of concurrent versions)

**Comment by xuorig** [comment]
fixed
