### ISSUE TITLE
Page 185: Hyphen used instead of 'a'

### ISSUE THREAD

**Issue by amaurycrickx** [xuorig/prg-feedback#19]
> The key point here is not to look at your new GraphQL API as - GraphQL version of your REST API, but instead just a new GraphQL interface to your domain and use cases.

Replace hyphen with 'a'
The key point here is not to look at your new GraphQL API as a GraphQL version of your REST API, but instead just a new GraphQL interface to your domain and use cases.

**Comment by xuorig** [comment]
v1.2, thanks for all these suggestions 🙇
