### ISSUE TITLE
Page 107 "We would cost" should be "We would have a wost of" or similar 

### ISSUE THREAD

**Issue by amaurycrickx** [xuorig/prg-feedback#2]
> For example, if a connection actually only returns 20 items, we would cost 20, but if it returned 99, we would cost 99.

I'd think the above sentence should read:
For example, if a connection actually only returns 20 items, we'd have a cost 20, but if it returned 99, the cost would be 99.

**Comment by xuorig** [comment]
fixed in v1.2
