### ISSUE TITLE
“Design” Chapter, “Naming” Section: “User” not fully refactored in example schema.

### ISSUE THREAD

**Issue by phyllisstein** [xuorig/prg-feedback#20]
The schema example in “Naming,” on page 33 of the PDF, factors `User` out into an interface, but the updated schema still uses it as a type:

```graphql
type Query {
	viewer: User!		# 💣
	team(id: ID!): Team
}
```

I believe it should read:

```graphql
type Query {
	viewer: Viewer!
	team(id: ID!): Team
}
```

**Comment by xuorig** [comment]
Thanks @phyllisstein! This will be fixed in v1.2. 🍻
