### ISSUE TITLE
Page 113 Consider rephrasing "some very common questions and problem organization issues hit, as to"

### ISSUE THREAD

**Issue by amaurycrickx** [xuorig/prg-feedback#8]
> When it’s time to enforce authorization in GraphQL APIs, some very common questions and problem organization issues hit, as to whether they should be enforced on a per-type or per-field basis.

Consider rephrasing to 
When it’s time to enforce authorization in GraphQL APIs, a very common question is whether they should be enforced on a per-type or per-field basis.

**Comment by xuorig** [comment]
Fixed in v1.2
