### ISSUE TITLE
Page 113 consider rephrasing "A lot of simple scalar fields on objects also have very similar permissions to each other."

### ISSUE THREAD

**Issue by amaurycrickx** [xuorig/prg-feedback#9]
> A lot of simple scalar fields on objects also have very similar permissions to each other.

Consider rephrasing to
Second, the simple scalar fields on a given object typically share the same set of required permissions.

**Comment by amaurycrickx** [comment]
For the next sentence:
> But most importantly, it’s very hard to track all possible ways to get to an object.

Consider rephrasing to
Most importantly, it’s very hard to track all _the_ possible ways to get to an object.

**Comment by amaurycrickx** [comment]
And the next sentence
> If we only make authorization checks at the field level,

I believe it should read 
If we only make authorization checks at field level,
("the" was removed)

**Comment by amaurycrickx** [comment]
Side note, I'm unsure whether checks are "made" or checks are "done"
See page 113
> There’s no doubt that some authorization checks may need to be done at the GraphQL layer.

I almost filed an issue to rephrase the above with "need to be made", but I'm not sure...

**Comment by amaurycrickx** [comment]
Next sentence:
> Here’s an example, which uses a simple @authorization directive to express to help visualize where authorization checks would happen:

Consider rephrasing to
Here’s an example which uses a simple @authorization directive to help visualize where authorization checks would happen:

(comma was also removed)

**Comment by xuorig** [comment]
TY! fixed in v1.2
